test: new bump-version logic 14

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,6 +61,7 @@ jobs:
           echo "Ref name: ${{ github.ref_name }}"
 
   draft_release:
+    if: needs.bump_version_check.outputs.should_run_tests_and_release == 'true'
     needs: [typechecking, tests]
     permissions:
       contents: write # Allows this job to create releases
@@ -111,3 +112,19 @@ jobs:
       run-number: ${{ github.run_number }}
       status: "completed"
       conclusion: ${{ needs.draft_release.result }}
+
+  check_release_status:
+    needs: [draft_release]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check draft_release result
+        run: |
+          result="${{ needs.draft_release.result }}"
+          echo "draft_release result: $result"
+          if [[ "$result" == "success" ]] || [[ "$result" == "skipped" ]]; then
+            echo "Release completed or skipped."
+          else
+            echo "Release failed (result: $result)"
+            exit 1
+          fi
